#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
#
# Complete the 'pairs' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY arr
#

def pairs_v2(k, arr):
    dictionary_nums = {}
    ansCount = 0 
    for i in arr:
        dictionary_nums[i] = i-k
        
    for i in dictionary_nums:
        if dictionary_nums[i] in dictionary_nums:
            ansCount += 1
    return ansCount
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    result = pairs_v2 (k, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
